[package]
name = "prng"
version = "0.0.5"
description = "Statistical pseudo-random number generators"
repository = "https://github.com/research-ag/prng"
keywords = [ "rand", "random", "rng", "sfc", "seiran" ]
license = "Apache-2.0"

[dependencies]
base = "0.11.2"

[dev-dependencies]
test = "2.0.0"
matchers = "https://github.com/kritzcreek/motoko-matchers#v1.3.0@3dac8a071b69e4e651b25a7d9683fe831eb7cffd"

[toolchain]
moc = "0.11.2"

[requirements]
moc = "0.11.0"

